trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: BuildTools

steps:
- task: PowerShell@2
  displayName: Install Build Tools
  inputs:
    targetType: inline
    script: |
      mkdir C:\BuildTools
      mkdir C:\BuildTools\Download

      (new-object net.webclient).DownloadFile(${env:OpenCV_URL}, 'C:/BuildTools/Download/OpenCV.7z')
      7z x C:\BuildTools\Download\OpenCV.7z -oC:\BuildTools\OpenCV

      (new-object net.webclient).DownloadFile(${env:Qt_URL}, 'C:/BuildTools/Download/Qt.7z')
      7z x C:\BuildTools\Download\Qt.7z -oC:\BuildTools\Qt

      (new-object net.webclient).DownloadFile(${env:Zlib_URL}, 'C:/BuildTools/Download/Zlib.7z')
      7z x C:\BuildTools\Download\Zlib.7z -oC:\BuildTools\Zlib

- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      git submodule update --init --recursive
      call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
      mkdir build
      cd build
      cmake -G "Visual Studio 17 2022" -DOpenCV_DIR=C:\BuildTools\OpenCV -DZLIB_ROOT=C:\BuildTools\Zlib -DOpenCV_STATIC=false -DENABLE_OPENGL=ON .. || exit /b
      cmake --build . --config %CONFIGURATION% || exit /b
      cpack -C %CONFIGURATION% --config ./CPackConfig.cmake || exit /b
      ctest -C %CONFIGURATION% -T Test --no-compress-output -E "KeyChain" || exit /b
      cd ..
      mkdir drop
      move build\silica-*.zip drop\
      move build\silica-*.exe drop\

- task: PublishTestResults@2
  inputs:
   testResultsFormat: CTest
   testResultsFiles: build/Testing/**/Test.xml
   failTaskOnFailedTests: true
   buildConfiguration: ${Configuration}      

- publish: drop/
